"""Create embeddings table

Revision ID: 20260326_0003
Revises: 20260326_0002
Create Date: 2026-03-26 12:10:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20260326_0003"
down_revision: Union[str, None] = "20260326_0002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "embeddings",
        sa.Column(
            "id", sa.UUID(), nullable=False, server_default=sa.text("gen_random_uuid()")
        ),
        sa.Column("content_type", sa.String(length=50), nullable=False),
        sa.Column("content_id", sa.UUID(), nullable=False),
        sa.Column("embedding_model", sa.String(length=100), nullable=True),
        sa.Column("embedding", sa.String(length=1536), nullable=False),
        sa.Column("text_chunk", sa.String(length=2000), nullable=True),
        sa.Column("chunk_index", sa.Integer(), nullable=True),
        sa.Column("extra_data", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("idx_content_type_id"),
        "embeddings",
        ["content_type", "content_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_content_type_id"), table_name="embeddings")
    op.drop_table("embeddings")
    # ### end Alembic commands ###
