"""Add synced_at to confluence_pages

Revision ID: 20260326_0002
Revises: 20260323_0001
Create Date: 2026-03-26 11:55:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260326_0002'
down_revision: Union[str, None] = '20260323_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('confluence_pages', sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('confluence_pages', 'synced_at')
    # ### end Alembic commands ###
